repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace
    - id: check-ast
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
        stages: [ commit ]
      - id: isort
        name: isort
        entry: poetry run isort --filter-files
        language: system
        types: [ python ]
        stages: [ commit ]
      - id: mypy
        name: mypy
        entry: poetry run mypy shikibaio
        pass_filenames: false
        language: system
        stages: [ commit ]